version: "3.0"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
  service-a:
    build: .
    restart: on-failure
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:8080
