spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: wkdWkddl1218

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

KEY:
  JWT: asjdflkasjdfkl123123
---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:mysql://db:3306/testdb
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect